smdk v1.3 release
Signed-off-by: KyungsanKim <ks0204.kim@samsung.com>
Signed-off-by: WonjaeLee <wj28.lee@samsung.com>
Signed-off-by: JunhyeokIm<junhyeok.im@samsung.com>
Signed-off-by: JongchanLim <jongchan.im@samsung.com>
Signed-off-by: SeungjunHa <seungjun.ha@samsung.com>
Signed-off-by: JeHoonPark <jehoon.park@samsung.com>
Signed-off-by: HoJinNam <hj96.nam@samsung.com>
Signed-off-by: DaeyoungKim <dy0.kim@samsung.com>

diff --git a/lib/cxl_cli/test/common b/lib/cxl_cli/test/common
--- a/lib/cxl_cli/test/common
+++ b/lib/cxl_cli/test/common
@@ -27,6 +27,18 @@ if [ -z $DAXCTL ]; then
 	fi
 fi
 
+# CXL
+if [ -z $CXL ]; then
+	if [ -f "../cxl/cxl" ] && [ -x "../cxl/cxl" ]; then
+		export CXL=../cxl/cxl
+	elif [ -f "./cxl/cxl" ] && [ -x "./cxl/cxl" ]; then
+		export CXL=./cxl/cxl
+	else
+		echo "Couldn't find a cxl binary"
+		exit 1
+	fi
+fi
+
 if [ -z $TEST_PATH ]; then
 	export TEST_PATH=.
 fi
